var age = "25";
var height = "5.7";
var num = 4;
var sum = parseInt(age) + num;
console.log(sum);
sum += parseFloat(height);
console.log(sum);
sum = String(sum);
console.log(sum + 100);
sum = Number(sum);
console.log(sum - 30);